# Generated by Django 6.0.5 on 2026-09-10 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('secret_key_hash', models.CharField(editable=False, max_length=128)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('order_reference', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('requires_payment', 'Requires payment'), ('succeeded', 'Succeeded'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='requires_payment', max_length=20)),
                ('redirect_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='paymentgateway.merchant')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.transaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merchant', 'idempotency_key'), name='uniq_merchant_idempotency')],
            },
        ),
    ]
